apiVersion: v1
kind: Namespace
metadata:
  name: gomonitor
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gomonitor-webhook
  namespace: gomonitor
  labels:
    app: gomonitor-manager
webhooks:
  - name: monitor.online.daq.ihep
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    # enable the example below to limit to namespaces with specific labels only
    # namespaceSelector:
    #   matchLabels:
    #     controller: gomonitor
    clientConfig:
      service:
        name: gomonitor-manager
        namespace: gomonitor
        path: "/mutate-v1-pod"
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2RENDQXFTZ0F3SUJBZ0lVVnY4TGloUjQ5ZTJzRFdOcmVPOVhKWGhLZU9rd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pERUxNQWtHQTFVRUJoTUNRMDR4RHpBTkJnTlZCQWdUQms5eVpXZHZiakVRTUE0R0ExVUVCeE1IUW1WcAphbWx1WnpFVE1CRUdBMVVFQ2hNS1MzVmlaWEp1WlhSbGN6RUxNQWtHQTFVRUN4TUNRMEV4RURBT0JnTlZCQU1UCkIzZGxZbWh2YjJzd0hoY05NakV3TmpBME1ETXhOREF3V2hjTk1qWXdOakF6TURNeE5EQXdXakJrTVFzd0NRWUQKVlFRR0V3SkRUakVQTUEwR0ExVUVDQk1HVDNKbFoyOXVNUkF3RGdZRFZRUUhFd2RDWldscWFXNW5NUk13RVFZRApWUVFLRXdwTGRXSmxjbTVsZEdWek1Rc3dDUVlEVlFRTEV3SkRRVEVRTUE0R0ExVUVBeE1IZDJWaWFHOXZhekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUxpOVpLQ2VVdUNSb3UzcGQycjU4Q3UKeWNVUDZoZlBCdllqb09RUVhHSVpmVzBPelplQldOOTI4MWhmTjRzSFVqWlg5M0UxVjM5dlBmTG0vRVVoa2ZtSgpucXpCMUs5MnZFdmdsZGhLRFhSRnh1MFFzMXNkSlhnWW56RTIyelVqWnc2TkFldTRlK1NreVZ1TWN0K28zMlYwCkNRNTZxRkx0R2h0M0ZQMElDK2EwUUdtN3dnTHg0Z3crbW9Idmc2SUR6azMzMmtsQ2xOUkJXTVJRZzBzZE8rSDcKU2Q4eHV4NnlJRDNNQVRxbytRei8raTNwZVIzeDFTd3JXelI5TEZGcFNCREp2UnpuZ1B0NHg5OWI1dSt4RXExWQpjSDRuTnVZdkNkaG5nYlJPZ0szTUcyVGJqMUVyai9laTVVUnRjTEFmZGR1WjA3S3hGVWdLbzNyRzlLSW5wYnNDCkF3RUFBYU5tTUdRd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFJd0hRWUQKVlIwT0JCWUVGTlFyQ1dNUVY2VU5uVXJKUWNuMWtJQWU5RGppTUI4R0ExVWRJd1FZTUJhQUZOUXJDV01RVjZVTgpuVXJKUWNuMWtJQWU5RGppTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBQThQbU1pVDNDVCtqazNxSk93bTJMCkNhVlAzMVpiVTkrcnBHN2p0UzRML0haMlZobTZuMzNQT2FJT1pBeUJGWlV6Yk5GT3ZFVWNOc1hVbHdiTXFMSkcKb3kwS2J1RmhaSTVqdi94bHFTMEgvQ0plZUIwZHk4czNCL3MxVHQwUmhUZGJ3RHI4ZEpxMWNzTG9ONkZCYUdDSwpWbUNmT1FWSmJHQkpRREJCVC9UMWl6bGJtYkNUV1BHQ2RyT2xoQzdsSTZUaTEzdFNIYjhRbHd3QnZ3UjFpUEdrCm5oZExxaCtqV0FIUXkybTJGYklZUzdJbHpWMTdFbGozZEpzbFA2OWdmWWlRRk13NDJ1TFBlU2hHbUppUlRHSWkKQ1Zjb3ZOSG5zSDlPTlBvSDlBUlVwa0hqRXlTS0dQVmg1UC9QU2IwdkxWaGU2aVc4VTV0bGttSmR4U0hEYVdxcgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]
    failurePolicy: Ignore
    reinvocationPolicy: IfNeeded
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: gomonitor-certs
  namespace: gomonitor
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVmakNDQTJhZ0F3SUJBZ0lVU3o2WGRMTkd0QTBSRTIxWSs3Q3hIbUlSTVRNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pERUxNQWtHQTFVRUJoTUNRMDR4RHpBTkJnTlZCQWdUQms5eVpXZHZiakVRTUE0R0ExVUVCeE1IUW1WcAphbWx1WnpFVE1CRUdBMVVFQ2hNS1MzVmlaWEp1WlhSbGN6RUxNQWtHQTFVRUN4TUNRMEV4RURBT0JnTlZCQU1UCkIzZGxZbWh2YjJzd0lCY05NakV3TmpBME1ETXhOREF3V2hnUE1qRXlNVEExTVRFd016RTBNREJhTUcweEN6QUoKQmdOVkJBWVRBa05PTVJNd0VRWURWUVFJRXdwTGRXSmxjbTVsZEdWek1SQXdEZ1lEVlFRSEV3ZENaV2xxYVc1bgpNUkF3RGdZRFZRUUtFd2RDWldscWFXNW5NUk13RVFZRFZRUUxFd3BMZFdKbGNtNWxkR1Z6TVJBd0RnWURWUVFECkV3ZDNaV0pvYjI5ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMlliQVAxN3gKTkVHbER0WHo3cHl3Z0lIRlVVMWNLWEZ1dGpxQ1BIK2FzSjgyMnB3TVRHSzNJYklWSGpURmw1S3RyYXU3SlNsbgpGUkd2NmkxTXZTS29WZUNSM05HbmFMblJBdnNlTTQrVHdTUThQeWlFMUtDNEkwUTRuKzZOZldlZWNRTU95L0tGCkdTRnRQd1NlbERHZ1NFYVExMUF3ODUwWUpqeXdYbjJ3Zms4b3RBc3ZBcTFLam5SYXlYY21talZPT0x3NnpKUVYKRjB3RHRVV3pwZnpySTdOdnJMaW5PVU1XY2JvYzRQajdhRGIxb2g1bzdSZmIxUk13RDdDMkVWUHVSbDJWaGo1Rgp4RTJxN09QcThpSGpVUjRKUWVDbG1HbGZIYm00bVkxMCtlRUQwSVpMT09nSTh2SGRRSkRUM3UwQ2FtRi9RUm44CllhaXFnQ1hXU0xrRzV3SURBUUFCbzRJQkd6Q0NBUmN3RGdZRFZSMFBBUUgvQkFRREFnV2dNQk1HQTFVZEpRUU0KTUFvR0NDc0dBUVVGQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRkJtWHhNMVE2YmpMT3NUSwpJZ2N1dGRINGp4NmJNQjhHQTFVZEl3UVlNQmFBRk5RckNXTVFWNlVOblVySlFjbjFrSUFlOURqaU1JR2hCZ05WCkhSRUVnWmt3Z1phQ0cyZHZiVzl1YVhSdmNpMXRZVzVoWjJWeUxtZHZiVzl1YVhSdmNvSWZaMjl0YjI1cGRHOXkKTFcxaGJtRm5aWEl1WjI5dGIyNXBkRzl5TG5OMlk0SW5aMjl0YjI1cGRHOXlMVzFoYm1GblpYSXVaMjl0YjI1cApkRzl5TG5OMll5NWpiSFZ6ZEdWeWdpMW5iMjF2Ym1sMGIzSXRiV0Z1WVdkbGNpNW5iMjF2Ym1sMGIzSXVjM1pqCkxtTnNkWE4wWlhJdWJHOWpZV3d3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUJaVnJveFNsY1hqZmFzenl3M0MKazFBUTJKUHl4d3ZwYmVPUnB0RjZrdVJjSHFSRFdZdUJMbXB6blMvNUp0V0JkZFhZS3BQYmh5dWRqU1NMR3hITgpVNGVZbm9ZTWNlSU54SWcrcHhlOWUvbEkvR0phNjJGbGIyMlFtMGdiWVNTREkvM0kxVStLcVl5TUFGVng2TU5JClp4cThib29xKzVGVXVSRkd3ZEU3MEdNME9sOVBxU2YrdzFUZVhMOFk3eXVMM0d2ZXhwWkpLRU1nNjluMWNVOVkKTFJFdzhrZ2lpbDc2N1c5MHd1b3FiUVJBY05YVFJsYXNYaU8yaTA4YTcwd25GRjlQU05ybnF5bFl3TmpHSVlSVApwcUI0bS9ZOHhrU1kzNGplWnBQUm8yKytqbmJxMlVJdXlpQkhuMGJrdVl6YXpqVzBJNnBSK25Qa0NwYWRSaHMwClArND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBMlliQVAxN3hORUdsRHRYejdweXdnSUhGVVUxY0tYRnV0anFDUEgrYXNKODIycHdNClRHSzNJYklWSGpURmw1S3RyYXU3SlNsbkZSR3Y2aTFNdlNLb1ZlQ1IzTkduYUxuUkF2c2VNNCtUd1NROFB5aUUKMUtDNEkwUTRuKzZOZldlZWNRTU95L0tGR1NGdFB3U2VsREdnU0VhUTExQXc4NTBZSmp5d1huMndmazhvdEFzdgpBcTFLam5SYXlYY21talZPT0x3NnpKUVZGMHdEdFVXenBmenJJN052ckxpbk9VTVdjYm9jNFBqN2FEYjFvaDVvCjdSZmIxUk13RDdDMkVWUHVSbDJWaGo1RnhFMnE3T1BxOGlIalVSNEpRZUNsbUdsZkhibTRtWTEwK2VFRDBJWkwKT09nSTh2SGRRSkRUM3UwQ2FtRi9RUm44WWFpcWdDWFdTTGtHNXdJREFRQUJBb0lCQVFEWEI4YnBuaUFRaVVmeQpWM3Z3aDhKTzlubW8rakU5NHAwUDFOekRrMXpHZGsxU1kyb2c1SUNsOVpXOHEyd2NmdW5qUVYwWnlralZZZ3VsCkVhekhWd2hUQkZFTW1jL0V6ZE1aQUVhRnI4dmU1TVFOcHk5UHhhVGhiK0lONzFLOUFmNTFOeEdjZUp3c0VJZ2YKQUtFR1c5eFhOaktlTmU1K0UvQTRkRXZnekp6NDdkSGZHZEFJZllhbXppUUZhYlBvRHdmVjB1dGtSbkFmaEJvbwpuZUtkT2FuaXo5ZU5tT1puL0dqVlIvMUY5WEhFZXA1NzJEM2tteVRpS0lRYW0yaVFVRXQzcWd0ZkJyVndrM1FVCkl2YlFEVmxjZ3NObzNpdVBFODBUMithQ1pDeExGS2ZZL2lRM09QMHRwTENuNndiYlVmSG1yRjR5YThNcW8vSUEKSDJuWHNFMVpBb0dCQU53ZUlSUGpDMXNJTFQwMEtoajVMNllUVGtuc1RSS2tuK3NUdElRNUFvY3pGU2d4empJaQp4N3VPbVlDdHVtYzRSejdVdHp4MUdyWllVZWdLdXpOb3hLUGNWTFRRdFJ3L0xacm02dUR5YUlsOWdCUFppUzJKCkx5RS92ZGVUUGxrR1VHdTFWUmlqaEdKL0xEem5EQlJYQ3BBZ1k2b21sdXF6QVFreE9ncjhrcmxqQW9HQkFQejgKZTAvM1dUTUE1dzN6NU5PTTRhS1VQa1RQVDJldHIvOW0xZGllTllsVzIzcW1seUNnMDJKUE5kdjdhQTRpd3F5MgpWc21wUjdXOG56M21KWnVWOXVHR1gzL0pJWkVsMTZYdktSTDNBcUJmdHRKdEZ0RDN6U2kxUUdpeUJTaFNtbk1XCjg4VXNEbkVWbEcrL1ZMM3MwOFVEREhJYVMzai9WalROaXRYbEl2V3RBb0dBV2dNNEk1bkZHd1RNK3lwSnpNeVoKMzZBbGM3VmVEekdpODg2ckV5YjlFYXlpQ2ozVHhFelV3SzRmdDY5VGVzSlk0Q2k4aGN5ZGo5T3VLdVc0aDkxZwpER0lkZ1pPWGZHV1prSzY5ZmgrakFCYUNPWnZMclFOY2NveE9aY21neFdiL25Bd2JNR2d0eXRtV2paRXVMMk1vCnZxZUFHaVNOc294ZzhCRmhXdnpPUTJFQ2dZRUFtZWdJSk9mM3JoMjRjemFUV1ZmMTFQQ1d5VW5OcHVkMWtNMUEKLzUyUU9GTk5CdHJlU2cxTlRCdWdTb295RFpkOEU1S0NUZ0RjRFdZSkFxRkc4OVpSOFhYTUYzT0hKa1I5WXdlUwpWMlZLaGNKMCtLTkJKRFA4N2UwR21DcmxGRmpjZVhQWExYYlYrbG9FaWM4K2dLVFpXSnU0TUpwcW05dksyQ2pMCmM4RUllYWtDZ1lFQW5EeHlCeWdLaHdzcXJlSENqZytqTExOSlR6b3UwbHYxcXFSYlcvL29DVFJ2MmV2SExWQVoKeUJOeFF6Q2lqME1jRS9YVTcvNkNaNDhzblAzdmNnd0VSd2J1dHNIU3REQ1UyUE14SGVBYSszWER0dXh5UkJ5Qgp1L1I1RWhTZzdVNWl5elphbzV4TnFjbmdHUzB2THdjZktIRUhMbXFPZjRzbXBFYnRnRzBneExrPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomonitor-manager
  namespace: gomonitor
spec:
  selector:
    matchLabels:
      app: gomonitor-manager
  template:
    metadata:
      labels:
        app: gomonitor-manager
    spec:
      containers:
      - name: gomonitor-manager
        image: 1445277435/gomonitor-manager:v0.0.1
        imagePullPolicy: Always
        env: 
          - name: REPORT_DBURL
            value: "http://10.2.201.22:30093"
          - name: REPORT_DBBUCKET
            value: test
          - name: REPORT_DBTOKEN
            value: tn6Wzb0myOEdfDgssoHVhi4Mxt4em8jCEO6GBzYzde5bZeEcmXkMgZqLovyPQCYM9KZhin-7A1mYktcdnntL9g==
          - name: REPORT_DBORG
            value: default
        volumeMounts:
          - name: certs
            readOnly: true
            mountPath: "/etc/certs"
      volumes:
      - name: certs
        secret:
          secretName: gomonitor-certs
---
apiVersion: v1
kind: Service
metadata:
  name: gomonitor-manager
  namespace: gomonitor
spec:
  selector:
    app: gomonitor-manager
  ports:
  - protocol: TCP
    port: 443
    targetPort: 9443